apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort  # Change as needed (ClusterIP, LoadBalancer)
  selector:
    app: myapp
  ports:
    - name: http  # ✅ REQUIRED: Add a name for each port
      port: 8000
      targetPort: 8000
      nodePort: 30200
  
